name: Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

env:
  GOLANG_VERSION: '>=1.18'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for git to push upgrade commit if not already deployed
      packages: write  # for pushing packages to GHCR, which is used by cd.apps.argoproj.io to avoid polluting Quay with tags
    if: github.repository == 'rahulssv/argo-cd'
    runs-on: ubuntu-20.04-ppc64le
    env:
      GOPATH: /home/runner/work/argo-cd/argo-cd
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          architecture: ppc64le
      - uses: actions/checkout@v3 # v3.2.0
        with:
          path: src/github.com/rahulssv/argo-cd

      # get image tag
      - run: echo "tag=$(cat ./VERSION)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        working-directory: ./src/github.com/rahulssv/argo-cd
        id: image

      # login
      - run: |
          docker login ghcr.io --username $USERNAME --password-stdin <<< "$PASSWORD"
          docker login quay.io --username "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_TOKEN"
        if: github.event_name == 'push'
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.RELEASE_QUAY_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.RELEASE_QUAY_TOKEN }}

      # build
      - uses: docker/setup-buildx-action@v2
      - run: |
          IMAGE_PLATFORMS=linux/ppc64le
          if [[ "${{ github.event_name }}" == "push" || "${{ contains(github.event.pull_request.labels.*.name, 'test-arm-image') }}" == "true" ]]
          then
            IMAGE_PLATFORMS=linux/ppc64le
          fi
          echo "Building image for platforms: $IMAGE_PLATFORMS"
          docker buildx build --platform $IMAGE_PLATFORMS --push="${{ github.event_name == 'push' }}" \
            -t ghcr.io/rahulssv/argo-cd/argocd:${{ steps.image.outputs.tag }} \
            -t quay.io/rahulssv/argocd:latest .
        working-directory: ./src/github.com/rahulssv/argo-cd

      # sign container images
      - name: Install cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b# v2.8.1
        with:
          cosign-release: 'v1.13.0'

      - name: Sign Argo CD latest image
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY quay.io/rahulssv/argocd:latest
          # Displays the public key to share.
          cosign public-key --key env://COSIGN_PRIVATE_KEY
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
        if: ${{ github.event_name == 'push' }}

      # deploy
      - run: git clone "https://$TOKEN@github.com/argoproj/argoproj-deployments"
        if: github.event_name == 'push'
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - run: |
          docker run -u $(id -u):$(id -g) -v $(pwd):/src -w /src --rm -t ghcr.io/rahulssv/argo-cd/argocd:${{ steps.image.outputs.tag }} kustomize edit set image quay.io/rahulssv/argocd=ghcr.io/rahulssv/argo-cd/argocd:${{ steps.image.outputs.tag }}
          git config --global user.email 'rahulvishwakarma1181@gmail.com'
          git config --global user.name 'rahulssc'
          git diff --exit-code && echo 'Already deployed' || (git commit -am 'Upgrade argocd to ${{ steps.image.outputs.tag }}' && git push)
        if: github.event_name == 'push'
        working-directory: argoproj-deployments/argocd
      # TODO: clean up old images once github supports it: https://github.community/t5/How-to-use-Git-and-GitHub/Deleting-images-from-GitHub-Package-Registry/m-p/41202/thread-id/9811
